import { processNotes, type NoteResult } from './noteEngine';
import { parseFiles, type ParsedFile, type ParsedFunction } from './astParser';
import { classifyFile, type Classification } from './classifier';

export interface ComposeInput {
  title: string;
  notes: string;
  files: Array<{ name: string; content: string }>;
  sourceRepo?: string;
  sourceCommit?: string;
}

export interface ComposeResult {
  markdown: string;
  structure: {
    title: string;
    notes: NoteResult;
    files: ParsedFile[];
    classifications: Classification[];
    parseErrors: Array<{ fileName: string; message: string; line: number | null }>;
    generatedAt: string;
  };
}

function fmtParams(fn: ParsedFunction): string {
  return fn.params
    .map((p) => `${p.name}${p.optional ? '?' : ''}${p.type ? `: ${p.type}` : ''}`)
    .join(', ');
}

function signature(fn: ParsedFunction): string {
  return `${fn.async ? 'async ' : ''}${fn.name}(${fmtParams(fn)})${fn.returnType ? `: ${fn.returnType}` : ''}`;
}

function renderFunction(fn: ParsedFunction, lines: string[]): void {
  lines.push(`#### \`${fn.name}\`${fn.exported ? '' : ' _(internal)_'}`, '');
  if (fn.doc) lines.push(fn.doc, '');
  lines.push('```ts', signature(fn), '```', '');
  if (fn.params.length) {
    lines.push('| Parameter | Type | Required |', '| --- | --- | --- |');
    for (const p of fn.params) {
      lines.push(`| \`${p.name}\` | ${p.type ?? '—'} | ${p.optional ? 'no' : 'yes'} |`);
    }
    lines.push('');
  }
  lines.push(`**Returns:** \`${fn.returnType ?? 'unknown'}\``, '');
}

export function compose(input: ComposeInput): ComposeResult {
  const notes = processNotes(input.notes ?? '');
  const { parsed, errors } = parseFiles(input.files ?? []);
  const classifications = parsed.map((f) => classifyFile(f));
  const generatedAt = new Date().toISOString();

  const lines: string[] = [];
  const push = (...xs: string[]) => lines.push(...xs);

  push(`# ${input.title}`, '');
  push(`> Generated by ADGVC · ${new Date(generatedAt).toUTCString()}`, '');

  for (const section of notes.sections) {
    push(`## ${section.title}`, '');
    for (const block of section.blocks) {
      if (block.code) push(block.text, '');
      else push(`- ${block.text}`);
    }
    push('');
  }

  const totalFns = parsed.reduce((n, f) => n + f.functions.length, 0);
  const totalClasses = parsed.reduce((n, f) => n + f.classes.length, 0);
  const totalIfaces = parsed.reduce((n, f) => n + f.interfaces.length, 0);

  if (parsed.length) {
    push('## API Reference', '');
    push(`Parsed **${parsed.length}** file(s): ${totalFns} function(s), ${totalClasses} class(es), ${totalIfaces} interface/type(s).`, '');

    parsed.forEach((file, idx) => {
      const role = classifications[idx];
      push(`### \`${file.fileName}\` · ${role.label}`, '');
      if (file.comments[0]) push(`_${file.comments[0]}_`, '');

      if (file.imports.length) {
        const deps = file.imports
          .map((im) => {
            const parts = [im.default, im.namespace ? `* as ${im.namespace}` : '', ...(im.named.length ? [`{ ${im.named.join(', ')} }`] : [])].filter(Boolean);
            return `\`${im.source}\`${parts.length ? ` (${parts.join(', ')})` : ''}`;
          })
          .join(', ');
        push(`**Dependencies:** ${deps}`, '');
      }

      if (file.react.isReact) {
        if (file.react.hooks.length) push(`**Hooks:** ${[...new Set(file.react.hooks.map((h) => h.name))].join(', ')}`);
        if (file.react.jsxElements.length) push(`**Renders:** ${file.react.jsxElements.slice(0, 12).join(', ')}`);
        if (file.react.eventHandlers.length) {
          push(`**Handlers:** ${file.react.eventHandlers.map((e) => `${e.event}${e.calls.length ? ` → ${e.calls.join('/')}` : ''}`).join(', ')}`);
        }
        push('');
      }

      if (file.functions.length) {
        push('**Functions**', '');
        for (const fn of file.functions) renderFunction(fn, lines);
      }

      for (const cls of file.classes) {
        push(`#### class \`${cls.name}\`${cls.superClass ? ` extends \`${cls.superClass}\`` : ''}`, '');
        if (cls.doc) push(cls.doc, '');
        if (cls.properties.length) {
          push('Properties:', '');
          for (const p of cls.properties) push(`- \`${p.static ? 'static ' : ''}${p.name}\`${p.type ? `: ${p.type}` : ''}`);
          push('');
        }
        for (const m of cls.methods) renderFunction({ ...m, name: `${cls.name}.${m.name}` }, lines);
      }

      for (const iface of file.interfaces) {
        push(`#### ${iface.kind} \`${iface.name}\``, '');
        if (iface.doc) push(iface.doc, '');
        if (iface.members.length) {
          push('| Field | Type | Required |', '| --- | --- | --- |');
          for (const m of iface.members) push(`| \`${m.name}\` | ${m.type ?? '—'} | ${m.optional ? 'no' : 'yes'} |`);
          push('');
        }
      }
    });
  }

  if (errors.length) {
    push('## Generation Notes', '');
    for (const e of errors) push(`- ⚠ Could not parse \`${e.fileName}\`${e.line ? ` (line ${e.line})` : ''}: ${e.message}`);
    push('');
  }

  push('---', '');
  const meta: string[] = [`Generated ${new Date(generatedAt).toUTCString()}`];
  if (input.sourceRepo) meta.push(`Source: \`${input.sourceRepo}\``);
  meta.push(input.sourceCommit ? `Commit: \`${input.sourceCommit}\`` : 'Commit: _pending first save_');
  push(`<sub>${meta.join(' · ')}</sub>`, '');

  const markdown = `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
  return {
    markdown,
    structure: { title: input.title, notes, files: parsed, classifications, parseErrors: errors, generatedAt },
  };
}